const projects = [
  { name: 'Un silencio bárbaro',
    image: require('../../assets/images/avatar/patrick.png'),
    started_date: '',
    complete_date: '',
    description: 'Blah description',
    website: 'https://wwww.booksonwall.art',
    website_icon: 'bookmark',
    stage: 0, // 0 => prospect, 1 => funded , 2 => started, 3 => complete  ,
  },
  { name: 'Los cantos Rodados',
    image: require('../../assets/images/avatar/patrick.png'),
    started_date: '',
    complete_date: '',
    description: 'Blah description',
    website: 'https://wwww.booksonwall.art',
    website_icon: 'github',
    stage: 0,
  },
  { name: 'BooksOnWall App',
    image: require('../../assets/images/avatar/patrick.png'),
    started_date: '',
    complete_date: '',
    description: 'Blah description',
    website: 'https://github.com/BooksOnWall/BooksOnWall',
    website_icon: 'github',
    stage: 2,
  },
  { name: 'BooksOnWall Create',
    image: require('../../assets/images/avatar/patrick.png'),
    started_date: '',
    complete_date: '',
    description: 'Blah description',
    website: 'https://create.booksonwall.art',
    website_icon: 'bookmark',
    stage: 3,
  },
  { name: 'BooksOnWall Server',
    image: require('../../assets/images/avatar/patrick.png'),
    started_date: '',
    complete_date: '',
    description: 'Blah description',
    website: 'https://create.booksonwall.art',
    website_icon: 'bookmark',
    stage: 3,
  },
  { name: 'BooksOnWall Desktop',
    image: require('../../assets/images/avatar/patrick.png'),
    started_date: '',
    complete_date: '',
    description: 'Blah description',
    website: null,
    stage: 0,
  },
  {
    name: 'BooksOnWall for Education',
    image: require('../../assets/images/avatar/patrick.png'),
    started_date: '',
    complete_date: '',
    description: 'Blah description',
    website: null,
    stage: 0,
  },
  {
    name: 'BooksOnWall for Tourism',
    image: require('../../assets/images/avatar/patrick.png'),
    started_date: '',
    complete_date: '',
    description: 'Blah description',
    website: null,
    stage: 0,
  },
  {
    name: 'BooksOnWall for Culture',
    image: require('../../assets/images/avatar/patrick.png'),
    started_date: '',
    complete_date: '',
    description: 'Blah description',
    website: null,
    stage: 0
  },
];
export default projects;
