const articles = [
  {
    date: '22 nov 2017',
    title: 'BooksOnWall has started !',
    header: 'My header',
    content: 'My beautiful content',
    categories: ['Press', 'News', 'Technology'],
    author: 'Tom Bouillut',
    images: [require('../../assets/images/avatar/patrick.png')],
  },
  {
    date: '22 dec 2017',
    title: 'BooksOnWall has started !',
    header: 'My header',
    content: 'My beautiful content',
    categories: ['Press'],
    author: 'Tom Bouillut',
    images: [require('../../assets/images/avatar/patrick.png')],
  },
  {
    date: '22 nov 2018',
    title: 'BooksOnWall has started !',
    header: 'My header',
    content: 'My beautiful content',
    categories: ['Press'],
    author: 'Tom Bouillut',
    images: [require('../../assets/images/avatar/patrick.png')],
  },
  {
    date: '22 nov 2019',
    title: 'BooksOnWall has started !',
    header: 'My header',
    content: 'My beautiful content',
    author: 'Tom Bouillut',
    categories: ['Press'],
    images: [require('../../assets/images/avatar/patrick.png')],
  },
  {
    date: '22 nov 20320',
    title: 'BooksOnWall has started !',
    header: 'My header',
    content: 'My beautiful content',
    author: 'Tom Bouillut',
    categories: ['Press'],
    images: [require('../../assets/images/avatar/patrick.png')],
  },
];
export default articles;
